### ISSUE TITLE
TrainerRoad RuntimeError: Input IsMale not found in form

### ISSUE THREAD

**Issue by krohn** [jaroslawhartman/withings-sync#48] opened 2022-01-02 21:18 UTC
While syncing to Garmin works very well (and I am super happy with it, thank you for your work!!), it fails repeatly with TrainerRoad reporting error `RuntimeError: Input IsMale not found in form`:

Here's the output with some tracelog output. 
Any ideas, what I could do? 

```
2022-01-02 22:06:50,284 - withings_sync.trainerroad - INFO - Logged into TrainerRoad as "XXXXXXXXXX"
Traceback (most recent call last):
  File "/home/pi/.local/bin/withings-sync", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/withings_sync/sync.py", line 196, in main
    sync(**vars(args))
  File "/home/pi/.local/lib/python3.7/site-packages/withings_sync/sync.py", line 170, in sync
    logging.info(f'Current TrainerRoad weight: {tr.weight} kg ')
  File "/home/pi/.local/lib/python3.7/site-packages/withings_sync/trainerroad.py", line 175, in weight
    values, token = self._read_profile()
  File "/home/pi/.local/lib/python3.7/site-packages/withings_sync/trainerroad.py", line 118, in _read_profile
    select_data[key] = self._parse_name(tree, key)
  File "/home/pi/.local/lib/python3.7/site-packages/withings_sync/trainerroad.py", line 76, in _parse_name
    raise RuntimeError('Input {} not found in form'.format(name))
RuntimeError: Input IsMale not found in form
```

It's a fresh install on Rasberry4 (`pip3 install withings-sync`).

**Comment by bouncingcastle** [comment] 2022-01-20 00:21
I'm experiencing the same issue

**Comment by darrencope** [comment] 2022-03-10 14:22
I recall hearing in one of the TrainerRoad podcasts that they recently did a bunch of work to allow for users to choose from multiple genders (bravo TR team!) whereas previously it was stored as a binary 'male' yes/no field. I'm sure this issue is related to that!

**Comment by longstone** [comment] 2022-03-31 20:07
There was a PR Merged: https://github.com/jaroslawhartman/withings-sync/pull/56 can you please retry if this error persists?

**Comment by darrencope** [comment] 2022-04-01 02:06
How do I test this change? I tried pip uninstall withings-sync followed by pip install withings-sync and am still seeing the issue. trainerroad.py does not show the change. If I manually overwrite trainerroad.py with the changed file, I get 
"RuntimeError: Failed to verify numerical key Weight"

**Comment by longstone** [comment] 2022-04-01 04:25
No Python release was done. So IT would not be Fixed. I'll See that we can get one. In the mean time you could either check out the repository and build the script or use docker.

**Comment by JoGu01** [comment] 2022-04-01 04:47
You can test with
```
pip uninstall withings-sync
python3 -m pip install git+https://github.com/jaroslawhartman/withings-sync/
```
Hope it helps.

**Comment by darrencope** [comment] 2022-04-01 14:22
Thanks JoGu01. I was able to test, and am now getting the following error:

RuntimeError: Failed to verify numerical key Weight when trying to sync to TrainerRoad.

**Comment by longstone** [comment] 2022-04-03 08:12
I suggest opening a new Issue with an excerpt from the log. The root cause (isMale) is fixed.

**Comment by stv0g** [comment] 2022-06-27 14:55
Closing this issue now as @longstone motivated

**Closed by stv0g** 2022-06-27 14:55 UTC
Labels: bug
