### ISSUE TITLE
TypeError during first sync

### ISSUE THREAD

**Issue by robertvanharten** [jaroslawhartman/withings-sync#75] opened 2022-07-07 09:12 UTC
I've downloaded the latest pip version and started a sync from Withings to Garmin (with option -f 2016-01-01)

I'm getting the following error:
```
2022-07-07 10:47:32,697 - withings - INFO - Get Measurements
Traceback (most recent call last):
  File "/Users/robertvh/Library/Python/3.9/bin/./withings-sync", line 8, in <module>
    sys.exit(main())
  File "/Users/robertvh/Library/Python/3.9/lib/python/site-packages/withings_sync/sync.py", line 396, in main
    sync()
  File "/Users/robertvh/Library/Python/3.9/lib/python/site-packages/withings_sync/sync.py", line 349, in sync
    last_weight, last_date_time, syncdata = prepare_syncdata(height, groups)
  File "/Users/robertvh/Library/Python/3.9/lib/python/site-packages/withings_sync/sync.py", line 248, in prepare_syncdata
    groupdata["weight"] / pow(groupdata["height"], 2), 1
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

It looks like the Withings API is returning entries with weight = null.

**Comment by haapmik** [comment] 2022-07-11 21:30
I also get the same error message with version 3.4.2.

This can be fixed by changing line 246 `if height and "weight" in groupdata:` to `if height and groupdata["weight"]:` in `withings-sync/sync.py`:

```python
        if height and groupdata["weight"]:
            groupdata["bmi"] = round(
                groupdata["weight"] / pow(groupdata["height"], 2), 1
            )
```

**Comment by longstone** [comment] 2022-07-12 05:50
I'll have a look.

**Comment by haapmik** [comment] 2022-07-13 16:38
@longstone : I tested that PR #76 and it fixes the problem.

**Closed** 2022-07-13 17:23 UTC
Labels: bug

**Comment by richo67** [comment] 2022-09-07 09:48
When I installed using pip I still have not got this fix and getting TypeError.

**Comment by wastlmuc** [comment] 2022-10-14 18:33
> When I installed using pip I still have not got this fix and getting TypeError.

This might be caused by setup.py not reflecting the latest version. It is still on *.2?
